/**
 * Burmese for the back-office consoles.
 *
 * Keyed by the English string exactly as the screen writes it, so a console
 * translates itself without every page importing a translator. Anything not
 * listed here stays in English rather than guessing — long methodology notes
 * in particular, where a loose translation would change what a rule means.
 *
 * Terms of art keep the form officers use: လိုင်စင် (licence), ခွင့်ပြုမိန့်
 * (permit), စည်းကမ်းလိုက်နာမှု (compliance), စာရင်းစစ် (audit).
 */
export const ADMIN_MM = {
  // ---------------------------------------------------------------- chrome
  'All portals': 'ပေါ်တယ်အားလုံး',
  'Leave portal': 'ပေါ်တယ်မှထွက်ရန်',
  'Switch identity': 'အသုံးပြုသူပြောင်းရန်',
  'No notifications': 'အကြောင်းကြားချက်မရှိပါ',
  'Search route, stop, vehicle…': 'လမ်းကြောင်း၊ မှတ်တိုင်၊ ယာဉ်ရှာရန်…',
  'Search…': 'ရှာရန်…',
  of: '၏',
  all: 'အားလုံး',
  Back: 'နောက်သို့',
  Cancel: 'မလုပ်တော့ပါ',
  Close: 'ပိတ်ရန်',
  Create: 'ဖန်တီးရန်',
  Edit: 'ပြင်ရန်',
  Copy: 'ကူးယူရန်',
  Download: 'ဒေါင်းလုဒ်',
  Downloads: 'ဒေါင်းလုဒ်များ',
  Build: 'တည်ဆောက်ရန်',
  Compose: 'ရေးသားရန်',
  Preview: 'အစမ်းကြည့်ရန်',
  Prev: 'ယခင်',
  Next: 'နောက်တစ်ခု',
  All: 'အားလုံး',
  Open: 'ဖွင့်ရန်',
  Renew: 'သက်တမ်းတိုးရန်',
  Approve: 'အတည်ပြုရန်',
  Acknowledge: 'လက်ခံမှတ်တမ်းတင်ရန်',
  Amend: 'ပြင်ဆင်ရန်',
  Bypass: 'ကျော်လွှားရန်',
  Respond: 'တုံ့ပြန်ရန်',
  Resolve: 'ဖြေရှင်းရန်',
  Reject: 'ငြင်းပယ်ရန်',
  Save: 'သိမ်းရန်',
  Submit: 'တင်သွင်းရန်',
  Search: 'ရှာရန်',
  Export: 'ထုတ်ယူရန်',
  Today: 'ယနေ့',

  // ------------------------------------------------------------- portals
  Dashboard: 'ဒက်ရှ်ဘုတ်',
  'Command center': 'ကွပ်ကဲရေးစင်တာ',
  'Live operations': 'တိုက်ရိုက်လည်ပတ်မှု',
  'Bus Operator Portal': 'ဘတ်စ်ကားကုမ္ပဏီပေါ်တယ်',
  'Authority Console': 'အာဏာပိုင်ကွန်ဆိုး',
  'Licensing Portal': 'လိုင်စင်ပေါ်တယ်',
  'Back office': 'ရုံးတွင်းလုပ်ငန်း',

  // ------------------------------------------------------- nav group names
  Overview: 'ခြုံငုံသုံးသပ်ချက်',
  Operations: 'လည်ပတ်မှု',
  Insight: 'သုံးသပ်ချက်',
  Registries: 'မှတ်ပုံတင်စာရင်းများ',
  Terminals: 'ဂိတ်များ',
  Commercial: 'စီးပွားဖြစ်',
  Administration: 'စီမံခန့်ခွဲရေး',
  'Fleet & people': 'ယာဉ်နှင့်ဝန်ထမ်း',
  'Network & sales': 'ကွန်ရက်နှင့်အရောင်း',
  'Safety & compliance': 'ဘေးကင်းရေးနှင့်စည်းကမ်း',
  'Licensing & money': 'လိုင်စင်နှင့်ငွေကြေး',

  // ------------------------------------------------------------ operations
  Fleet: 'ယာဉ်အစု',
  Vehicles: 'ယာဉ်များ',
  'Add vehicle': 'ယာဉ်ထည့်ရန်',
  'Back to fleet': 'ယာဉ်အစုသို့ပြန်',
  Maintenance: 'ပြုပြင်ထိန်းသိမ်းမှု',
  Drivers: 'ယာဉ်မောင်းများ',
  Driver: 'ယာဉ်မောင်း',
  'Drivers available': 'အသင့်ရှိယာဉ်မောင်း',
  'Drivers licensed': 'လိုင်စင်ရယာဉ်မောင်း',
  'Drivers on duty': 'တာဝန်ကျယာဉ်မောင်း',
  Roster: 'တာဝန်ဇယား',
  Routes: 'လမ်းကြောင်းများ',
  Route: 'လမ်းကြောင်း',
  Schedules: 'အချိန်ဇယားများ',
  'Seat inventory': 'ထိုင်ခုံစာရင်း',
  Bookings: 'ကြိုတင်မှာယူမှုများ',
  'Bookings & manifest': 'မှာယူမှုနှင့်ခရီးသည်စာရင်း',
  Refunds: 'ငွေပြန်အမ်းမှုများ',
  Boarding: 'ကားပေါ်တက်ခြင်း',
  'Boarding & check-in': 'ကားပေါ်တက်ခြင်းနှင့်စစ်ဆေးခြင်း',
  'Boarding point': 'တက်မည့်နေရာ',
  Boardings: 'တက်ရောက်မှုများ',
  Boarded: 'တက်ပြီး',
  'Boarded this session': 'ဤအကြိမ်တွင်တက်ပြီး',
  'Boarding soon': 'မကြာမီတက်ရမည်',
  'Buses on road': 'လမ်းပေါ်ရှိကားများ',
  'Buses transmitting': 'အချက်ပြနေသောကားများ',
  Depot: 'ကားဂိတ်ရုံ',
  'Depots and scale': 'ကားဂိတ်ရုံနှင့်အရွယ်အစား',
  Capacity: 'ဆံ့နိုင်မှု',
  Deviating: 'လမ်းကြောင်းလွဲ',
  Bunching: 'ကားစုပြုံ',
  Departures: 'ထွက်ခွာမှုများ',
  'Departures today': 'ယနေ့ထွက်ခွာမှု',
  'Departure board': 'ထွက်ခွာချိန်ပြဘုတ်',
  'Add departure': 'ထွက်ခွာချိန်ထည့်ရန်',
  Departed: 'ထွက်ခွာပြီး',
  Bay: 'ဆိုက်ကပ်နေရာ',
  Bays: 'ဆိုက်ကပ်နေရာများ',
  'Bay allocation': 'ဆိုက်ကပ်နေရာခွဲဝေမှု',
  'Bay utilisation': 'ဆိုက်ကပ်နေရာအသုံးချမှု',
  'Bays unassigned': 'မသတ်မှတ်ရသေးသောနေရာ',
  Board: 'ပြဘုတ်',
  'Bus gate-in': 'ကားဂိတ်ဝင်',
  'Bus gate-out': 'ကားဂိတ်ထွက်',
  'Check-in': 'စစ်ဆေးဝင်ရောက်',
  'Checked in': 'ဝင်ရောက်ပြီး',
  'Check-ins today': 'ယနေ့ဝင်ရောက်မှု',
  'Checked in today': 'ယနေ့ဝင်ရောက်ပြီး',
  'Gate check-in': 'ဂိတ်ဝင်စစ်ဆေးမှု',
  'Crowd level': 'လူစည်ကားမှုအဆင့်',
  'Crowd monitor': 'လူစည်ကားမှုစောင့်ကြည့်',
  'Expected passengers': 'မျှော်မှန်းခရီးသည်',
  'Expected on this run': 'ဤခရီးစဉ်တွင်မျှော်မှန်း',
  'Expected on next departure': 'နောက်ထွက်ခွာမှုတွင်မျှော်မှန်း',
  'Cash passenger': 'ငွေသားခရီးသည်',
  'Cash passengers': 'ငွေသားခရီးသည်များ',
  'Counter sale': 'ကောင်တာရောင်းချမှု',
  Scanner: 'စကင်နာ',
  Passenger: 'ခရီးသည်',
  Seat: 'ထိုင်ခုံ',
  Concession: 'လျှော့ဈေး',
  Concessions: 'လျှော့ဈေးများ',
  'Child under 6': '၆နှစ်အောက်ကလေး',
  'Elderly (60+)': 'သက်ကြီးရွယ်အို (၆၀+)',
  Disability: 'မသန်စွမ်း',

  // ---------------------------------------------------------- safety & SOS
  'Active SOS': 'လက်ရှိအရေးပေါ်',
  'SOS live board': 'အရေးပေါ်တိုက်ရိုက်ဘုတ်',
  Incidents: 'ဖြစ်စဉ်များ',
  'Open incidents': 'မပိတ်ရသေးသောဖြစ်စဉ်',
  'SOS & incidents': 'အရေးပေါ်နှင့်ဖြစ်စဉ်',
  'Close incident': 'ဖြစ်စဉ်ပိတ်ရန်',
  'Close with reason': 'အကြောင်းပြချက်ဖြင့်ပိတ်ရန်',
  'Call reporter back': 'သတင်းပို့သူကိုပြန်ခေါ်ရန်',
  'Dispatched today': 'ယနေ့စေလွှတ်ပြီး',
  Escalated: 'အဆင့်မြှင့်တင်ပြီး',
  'Escalated to the authority': 'အာဏာပိုင်ထံအဆင့်မြှင့်ပြီး',
  'Acknowledge overdue': 'သတ်မှတ်ချိန်ကျော်',
  'Acknowledge vs SLA': 'လက်ခံချိန်နှင့် SLA',
  'Acknowledged within SLA': 'SLA အတွင်းလက်ခံပြီး',
  'Acknowledgement SLAs': 'လက်ခံမှု SLA များ',
  'Breaching SLA': 'SLA ချိုးဖောက်',
  Enforcement: 'အရေးယူဆောင်ရွက်မှု',
  'e-Fines': 'အီလက်ထရွန်နစ်ဒဏ်ကြေး',

  // ------------------------------------------------------------ compliance
  Compliance: 'စည်းကမ်းလိုက်နာမှု',
  'Compliance matrix': 'စည်းကမ်းလိုက်နာမှုဇယား',
  'Compliant today': 'ယနေ့စည်းကမ်းညီ',
  Coverage: 'အချက်ပြလွှမ်းခြုံမှု',
  'Coverage %': 'လွှမ်းခြုံမှု %',
  'Coverage Index': 'လွှမ်းခြုံမှုညွှန်းကိန်း',
  'Coverage by line': 'လမ်းကြောင်းအလိုက်လွှမ်းခြုံမှု',
  'Coverage by region': 'တိုင်းဒေသအလိုက်လွှမ်းခြုံမှု',
  'Coverage at build': 'ထုတ်ချိန်လွှမ်းခြုံမှု',
  Finding: 'တွေ့ရှိချက်',
  Findings: 'တွေ့ရှိချက်များ',
  'Findings and disputes': 'တွေ့ရှိချက်နှင့်အငြင်းပွားမှု',
  'Findings awaiting reply': 'ဖြေကြားရန်စောင့်နေသောတွေ့ရှိချက်',
  'Findings issued': 'ထုတ်ပြန်ပြီးတွေ့ရှိချက်',
  'Dispute this finding': 'ဤတွေ့ရှိချက်ကိုအငြင်းဆိုရန်',
  'Dispute with evidence': 'သက်သေအထောက်အထားဖြင့်အငြင်းဆိုရန်',
  Disputes: 'အငြင်းပွားမှုများ',
  Appeals: 'အယူခံများ',
  'Appeals filed': 'တင်သွင်းပြီးအယူခံ',
  'Appeal this decision': 'ဤဆုံးဖြတ်ချက်ကိုအယူခံရန်',
  'File an appeal': 'အယူခံတင်သွင်းရန်',
  'Decisions you can appeal': 'အယူခံနိုင်သောဆုံးဖြတ်ချက်များ',
  Exceptions: 'ခြွင်းချက်များ',
  'Exceptions queue': 'ခြွင်းချက်တန်းစီ',
  'Dimensions in breach': 'ချိုးဖောက်နေသောအညွှန်းများ',
  'Audit log': 'စာရင်းစစ်မှတ်တမ်း',

  // ------------------------------------------------------------- licensing
  Applicant: 'လျှောက်ထားသူ',
  Application: 'လျှောက်လွှာ',
  Applications: 'လျှောက်လွှာများ',
  applications: 'လျှောက်လွှာများ',
  'Application details': 'လျှောက်လွှာအသေးစိတ်',
  'Application tracker': 'လျှောက်လွှာခြေရာခံ',
  'Application not found': 'လျှောက်လွှာမတွေ့ပါ',
  'Applications by licence type': 'လိုင်စင်အမျိုးအစားအလိုက်',
  'Applications by state': 'အခြေအနေအလိုက်လျှောက်လွှာ',
  'Applications in flight': 'ဆောင်ရွက်ဆဲလျှောက်လွှာ',
  'Applications in progress': 'ဆောင်ရွက်ဆဲလျှောက်လွှာ',
  'Approval rate': 'အတည်ပြုနှုန်း',
  'Approve and issue e-permit': 'အတည်ပြုပြီးခွင့်ပြုမိန့်ထုတ်ရန်',
  'Approved by': 'အတည်ပြုသူ',
  'Work queue': 'လုပ်ငန်းတန်းစီ',
  'Back to queue': 'တန်းစီသို့ပြန်',
  Inspections: 'စစ်ဆေးမှုများ',
  'Licence register': 'လိုင်စင်မှတ်ပုံတင်',
  'Permit register': 'ခွင့်ပြုမိန့်မှတ်ပုံတင်',
  Permit: 'ခွင့်ပြုမိန့်',
  'E-Permit': 'အီလက်ထရွန်နစ်ခွင့်ပြုမိန့်',
  'e-Receipt': 'အီလက်ထရွန်နစ်ပြေစာ',
  Holder: 'ကိုင်ဆောင်သူ',
  'Licence to': 'လိုင်စင်ပေးအပ်သူ',
  'Fee schedule': 'အခကြေးငွေဇယား',
  Fee: 'အခကြေးငွေ',
  'Fees collected': 'ကောက်ခံရရှိငွေ',
  'Document vault': 'စာရွက်စာတမ်းသိုလှောင်ခန်း',
  Document: 'စာရွက်စာတမ်း',
  Documents: 'စာရွက်စာတမ်းများ',
  'Docs expiring ≤ 60 days': '၆၀ရက်အတွင်းကုန်ဆုံးမည့်စာရွက်',
  'Expiring licences': 'သက်တမ်းကုန်နီးလိုင်စင်',
  'Expiring permits': 'သက်တမ်းကုန်နီးခွင့်ပြုမိန့်',
  'Expiring ≤ 30 days': '၃၀ရက်အတွင်းကုန်ဆုံး',
  'Expiring ≤ 90 days': '၉၀ရက်အတွင်းကုန်ဆုံး',
  Expires: 'ကုန်ဆုံးမည့်ရက်',
  Expiry: 'သက်တမ်း',
  'Days left': 'ကျန်ရက်',
  Effective: 'အကျိုးသက်ရောက်',
  'Effective from': 'စတင်အကျိုးသက်ရောက်သည့်ရက်',

  // ----------------------------------------------------------- money & ads
  Finance: 'ဘဏ္ဍာရေး',
  'Finance & settlement': 'ဘဏ္ဍာရေးနှင့်ရှင်းလင်းမှု',
  'Settlement oversight': 'ရှင်းလင်းမှုကြီးကြပ်ရေး',
  'Regulated revenue': 'ထိန်းညှိထားသောဝင်ငွေ',
  'Ad revenue': 'ကြော်ငြာဝင်ငွေ',
  'Ad revenue booked': 'မှာယူပြီးကြော်ငြာဝင်ငွေ',
  'Ad revenue trend': 'ကြော်ငြာဝင်ငွေလမ်းကြောင်း',
  'Ad campaigns': 'ကြော်ငြာလှုပ်ရှားမှုများ',
  'Ads & promotions': 'ကြော်ငြာနှင့်အထူးကမ်းလှမ်းချက်',
  'Ads & content approval': 'ကြော်ငြာနှင့်အကြောင်းအရာအတည်ပြုမှု',
  'Advertising revenue': 'ကြော်ငြာဝင်ငွေ',
  'Advertising policy': 'ကြော်ငြာမူဝါဒ',
  Advertiser: 'ကြော်ငြာရှင်',
  'Advertiser accounts': 'ကြော်ငြာရှင်အကောင့်များ',
  'Advertiser invoices': 'ကြော်ငြာရှင်ငွေတောင်းခံလွှာ',
  'Add advertiser': 'ကြော်ငြာရှင်ထည့်ရန်',
  'Add an advertiser': 'ကြော်ငြာရှင်တစ်ဦးထည့်ရန်',
  Campaign: 'ကြော်ငြာလှုပ်ရှားမှု',
  Campaigns: 'ကြော်ငြာလှုပ်ရှားမှုများ',
  'Book a campaign': 'ကြော်ငြာနေရာမှာယူရန်',
  'Book slot': 'နေရာမှာယူရန',
  Slot: 'နေရာ',
  Impressions: 'မြင်တွေ့မှုအရေအတွက်',
  Clicks: 'နှိပ်မှုအရေအတွက်',
  'Click-through': 'နှိပ်မှုနှုန်း',
  Budget: 'ဘတ်ဂျက်',
  'Billing & revenue split': 'ငွေတောင်းခံမှုနှင့်ဝင်ငွေခွဲဝေမှု',
  Billing: 'ငွေတောင်းခံမှု',
  Invoice: 'ငွေတောင်းခံလွှာ',
  'All invoices': 'ငွေတောင်းခံလွှာအားလုံး',
  Amount: 'ပမာဏ',
  'Amounts held': 'ထိန်းသိမ်းထားသောပမာဏ',
  Collected: 'ကောက်ခံပြီး',
  'Authority share': 'အာဏာပိုင်ဝေစု',
  'Authority floor': 'အာဏာပိုင်အနိမ့်ဆုံးနှုန်း',
  'Effective take rate': 'အမှန်တကယ်ရရှိနှုန်း',
  'Failed payouts': 'မအောင်မြင်သောငွေပေးချေမှု',
  'Change settlement account': 'ရှင်းလင်းရေးအကောင့်ပြောင်းရန်',
  'Download statement': 'ငွေစာရင်းရှင်းတမ်းဒေါင်းလုဒ်',
  Bank: 'ဘဏ်',
  'Bank ref': 'ဘဏ်ကိုးကား',
  Basis: 'တွက်ချက်ပုံ',
  Ceiling: 'အမြင့်ဆုံးနှုန်း',
  Fare: 'စီးခ',
  'Fare bands': 'စီးခအပိုင်းအခြား',
  'Fares & promos': 'စီးခနှင့်အထူးကမ်းလှမ်းချက်',
  'Fares & promotions': 'စီးခနှင့်အထူးကမ်းလှမ်းချက်',
  'Fares by line': 'လမ်းကြောင်းအလိုက်စီးခ',
  'Fares outside band': 'အပိုင်းအခြားပြင်ပစီးခ',
  'Average band width': 'ပျမ်းမျှအပိုင်းအခြားအကျယ်',
  'Average price position': 'ပျမ်းမျှဈေးနှုန်းအနေအထား',
  Discount: 'လျှော့ဈေး',
  'Approve refund': 'ငွေပြန်အမ်းမှုအတည်ပြုရန်',

  // ------------------------------------------------------- content & comms
  'Announcements & alerts': 'ကြေညာချက်နှင့်သတိပေးချက်',
  'Announcements & service alerts': 'ကြေညာချက်နှင့်ဝန်ဆောင်မှုသတိပေးချက်',
  Alerts: 'သတိပေးချက်များ',
  'Content & alerts': 'အကြောင်းအရာနှင့်သတိပေးချက်',
  'Content live now': 'ယခုထုတ်လွှင့်နေသောအကြောင်းအရာ',
  Broadcast: 'အစုလိုက်ပို့ခြင်း',
  Broadcasts: 'အစုလိုက်ပို့ချက်များ',
  'Broadcast to drivers': 'ယာဉ်မောင်းများထံပို့ရန်',
  'Delivery logs': 'ပေးပို့မှုမှတ်တမ်း',
  'Delivery rate': 'ပေးပို့အောင်မြင်နှုန်း',
  'Delivery by advertiser': 'ကြော်ငြာရှင်အလိုက်ပေးပို့မှု',
  Delivered: 'ပေးပို့ပြီး',
  delivered: 'ပေးပို့ပြီး',
  'Fallback to SMS': 'SMS သို့ပြောင်းပေးပို့',
  Channel: 'လမ်းကြောင်း',
  Channels: 'လမ်းကြောင်းများ',
  'Channel quotas': 'လမ်းကြောင်းအလိုက်ကန့်သတ်ချက်',
  'By channel': 'လမ်းကြောင်းအလိုက်',
  Audience: 'ပစ်မှတ်အုပ်စု',
  Cadence: 'ပေးပို့အကြိမ်ရေ',
  Attempts: 'ကြိုးပမ်းမှုအကြိမ်',
  FAQs: 'မေးလေ့ရှိသောမေးခွန်းများ',
  'FAQs & legal pages': 'မေးခွန်းများနှင့်ဥပဒေစာမျက်နှာ',
  'Chatbot KB': 'ချက်ဘော့အသိပညာစုစည်းမှု',
  'Chatbot knowledge base': 'ချက်ဘော့အသိပညာစုစည်းမှု',
  'Chatbot containment': 'ချက်ဘော့ဖြေရှင်းနိုင်မှု',
  'App home layout': 'အက်ပ်ပင်မစာမျက်နှာအပြင်အဆင်',
  'Active ticket card': 'အသုံးပြုဆဲလက်မှတ်ကတ်',
  Library: 'စာကြည့်တိုက်',
  Helpdesk: 'အကူအညီဌာန',
  Complaints: 'တိုင်ကြားချက်များ',
  'Complaints oversight': 'တိုင်ကြားချက်ကြီးကြပ်မှု',

  // ---------------------------------------------------------- insight & AI
  Analytics: 'ခွဲခြမ်းစိတ်ဖြာမှု',
  Planning: 'စီမံကိန်းရေးဆွဲမှု',
  Reports: 'အစီရင်ခံစာများ',
  'Report builder': 'အစီရင်ခံစာဖန်တီးကိရိယာ',
  'Build report': 'အစီရင်ခံစာထုတ်ရန်',
  'National dashboard': 'အမျိုးသားအဆင့်ဒက်ရှ်ဘုတ်',
  'Regional dashboard': 'တိုင်းဒေသအဆင့်ဒက်ရှ်ဘုတ်',
  'Central admin dashboard': 'ဗဟိုစီမံခန့်ခွဲမှုဒက်ရှ်ဘုတ်',
  'CMS overview': 'CMS ခြုံငုံသုံးသပ်ချက်',
  'AI & automation': 'AI နှင့်အလိုအလျောက်စနစ်',
  'AI demand forecast': 'AI ဝယ်လိုအားခန့်မှန်းချက်',
  Assistants: 'အကူအညီပေးစနစ်များ',
  Guardrails: 'ကာကွယ်ရေးစည်းမျဉ်း',
  Demand: 'ဝယ်လိုအား',
  'Area comparison': 'ဧရိယာနှိုင်းယှဉ်ချက်',
  'By area': 'ဧရိယာအလိုက်',
  'By state': 'အခြေအနေအလိုက်',
  'By licence type': 'လိုင်စင်အမျိုးအစားအလိုက်',
  'Busiest journeys': 'အများဆုံးသွားလာသောခရီးစဉ်',
  'Corridor speed by two-hour window': 'နှစ်နာရီအလိုက်လမ်းကြောင်းအမြန်နှုန်း',
  Corridor: 'လမ်းကြောင်းစု',
  'Candidate corridors': 'ဖြစ်နိုင်ခြေရှိလမ်းကြောင်းများ',
  'BRT corridors': 'BRT လမ်းကြောင်းများ',
  'Export corridor dossier': 'လမ်းကြောင်းအချက်အလက်ထုတ်ယူရန်',
  'Export per-line figures': 'လမ်းကြောင်းအလိုက်ကိန်းဂဏန်းထုတ်ယူရန်',
  'Average rating': 'ပျမ်းမျှအဆင့်သတ်မှတ်ချက်',
  Rating: 'အဆင့်သတ်မှတ်ချက်',
  'Below 3 ★': '၃ ကြယ်အောက်',
  Reviews: 'သုံးသပ်ချက်များ',
  'Daily, last 14 days': 'နေ့စဉ်၊ နောက်ဆုံး ၁၄ ရက်',

  // ----------------------------------------------------------- admin & org
  Company: 'ကုမ္ပဏီ',
  'Company profile': 'ကုမ္ပဏီအချက်အလက်',
  'Company KYC': 'ကုမ္ပဏီအထောက်အထားစိစစ်မှု',
  Operator: 'ကုမ္ပဏီ',
  Accounts: 'အကောင့်များ',
  'Add a user': 'အသုံးပြုသူထည့်ရန်',
  'Add user': 'အသုံးပြုသူထည့်ရန်',
  'Add account': 'အကောင့်ထည့်ရန်',
  'Add an account': 'အကောင့်တစ်ခုထည့်ရန်',
  'All app users': 'အက်ပ်အသုံးပြုသူအားလုံး',
  'Create account': 'အကောင့်ဖွင့်ရန်',
  'API & webhooks': 'API နှင့် webhooks',
  'API keys': 'API သော့များ',
  'Create key': 'သော့ဖန်တီးရန်',
  'Backend services': 'နောက်ကွယ်ဝန်ဆောင်မှုများ',
  'Feature flags': 'လုပ်ဆောင်ချက်ခလုတ်များ',
  Devices: 'ကိရိယာများ',
  '2FA': 'နှစ်ဆင့်အတည်ပြုမှု',
  Email: 'အီးမေးလ်',
  Contact: 'ဆက်သွယ်ရန်',
  Facilities: 'အဆောက်အအုံများ',
  Amenities: 'အဆင်ပြေမှုများ',
  Accessibility: 'အသုံးပြုနိုင်စွမ်း',
  'Accessibility follow-up': 'အသုံးပြုနိုင်စွမ်းဆက်လက်ဆောင်ရွက်ရန်',

  // ---------------------------------------------------------- table fields
  Status: 'အခြေအနေ',
  Type: 'အမျိုးအစား',
  Line: 'လမ်းကြောင်း',
  Class: 'အဆင့်',
  Category: 'အမျိုးအစား',
  Categories: 'အမျိုးအစားများ',
  Code: 'ကုဒ်',
  Date: 'ရက်စွဲ',
  When: 'အချိန်',
  From: 'မှ',
  Subject: 'အကြောင်းအရာ',
  Action: 'လုပ်ဆောင်ချက်',
  Actor: 'ဆောင်ရွက်သူ',
  Actual: 'အမှန်တကယ်',
  Entity: 'အကြောင်းအရာ',
  Entries: 'မှတ်တမ်းများ',
  Event: 'ဖြစ်ရပ်',
  Engine: 'အင်ဂျင်',
  Role: 'ရာထူး',
  Ticket: 'လက်မှတ်',
  Location: 'တည်နေရာ',
  Scope: 'နယ်ပယ်',
  SLA: 'SLA',
  Issued: 'ထုတ်ပြန်ပြီး',
  Valid: 'သက်တမ်းရှိ',
  Blocked: 'ပိတ်ပင်ထား',
  'Blocks bus': 'ကားကိုပိတ်ပင်သည်',
  Fail: 'မအောင်မြင်',
  Failed: 'မအောင်မြင်ပါ',
  'Awaiting action': 'ဆောင်ရွက်ရန်စောင့်ဆိုင်း',
  'Awaiting approval': 'အတည်ပြုရန်စောင့်ဆိုင်း',
  'Awaiting your reply': 'သင့်အဖြေကိုစောင့်နေသည်',
  'Assigned to': 'တာဝန်ပေးအပ်ခံရသူ',
  'Assignments with a conflict': 'ပဋိပက္ခရှိတာဝန်ခွဲဝေမှု',
  Allocation: 'ခွဲဝေမှု',
  Conflicts: 'ပဋိပက္ခများ',
  Affects: 'သက်ရောက်မှု',
  Enabled: 'ဖွင့်ထား',
  'Bago Region': 'ပဲခူးတိုင်းဒေသကြီး',
  BRT: 'BRT',
  'Data in': 'ဝင်ရောက်အချက်အလက်',
  'Data out': 'ထွက်ခွာအချက်အလက်',
  'Degraded or down': 'ချို့ယွင်းသို့မဟုတ်ရပ်ဆိုင်း',
  'Add to dossier': 'အချက်အလက်တွဲသို့ထည့်ရန်',
  'Automatic registry validation': 'မှတ်ပုံတင်အလိုအလျောက်စစ်ဆေးမှု',
  'Amend slack': 'ခွင့်ပြုချက်ပြင်ဆင်ရန်',
  Built: 'တည်ဆောက်ပြီး',
  'Built by': 'တည်ဆောက်သူ',
  Arrivals: 'ရောက်ရှိမှုများ',

  // ------------------------------------------------------------- batch 2
  Active: 'အသုံးပြုဆဲ',
  Approved: 'အတည်ပြုပြီး',
  Closed: 'ပိတ်ပြီး',
  Held: 'ထိန်းထား',
  Paid: 'ပေးချေပြီး',
  Pending: 'ဆိုင်းငံ့',
  Pass: 'အောင်',
  Planned: 'စီစဉ်ထား',
  Operational: 'လည်ပတ်နေ',
  Live: 'တိုက်ရိုက်',
  'Not measurable': 'တိုင်းတာ၍မရ',
  'Not responding': 'အချက်ပြမရ',
  'On headway': 'အချိန်မှန်',
  'On time': 'အချိန်မှန်',
  'On-time': 'အချိန်မှန်',
  Inspection: 'စစ်ဆေးမှု',
  'Inspection failed': 'စစ်ဆေးမှုမအောင်',
  'Inspection passed': 'စစ်ဆေးမှုအောင်',
  Inspector: 'စစ်ဆေးရေးမှူး',
  'Booked revenue': 'မှာယူပြီးဝင်ငွေ',
  Gross: 'စုစုပေါင်း',
  'Gross MMK': 'စုစုပေါင်း MMK',
  'gross MMK': 'စုစုပေါင်း MMK',
  'Gross ad revenue': 'စုစုပေါင်းကြော်ငြာဝင်ငွေ',
  'Gross sales': 'စုစုပေါင်းရောင်းရငွေ',
  'Gross sales (yesterday)': 'မနေ့ကရောင်းရငွေ',
  'Gross ticket sales today': 'ယနေ့လက်မှတ်ရောင်းရငွေ',
  'Gross vs net': 'စုစုပေါင်းနှင့်အသားတင်',
  'Government billing': 'အစိုးရငွေတောင်းခံမှု',
  'Government levy': 'အစိုးရအခွန်',
  'Government levy (14 days)': 'အစိုးရအခွန် (၁၄ရက်)',
  Levy: 'အခွန်',
  'Levy MMK': 'အခွန် MMK',
  'Levy by route class': 'လမ်းကြောင်းအဆင့်အလိုက်အခွန်',
  Licence: 'လိုင်စင်',
  Licences: 'လိုင်စင်များ',
  'Licence type': 'လိုင်စင်အမျိုးအစား',
  'Licence fees': 'လိုင်စင်ကြေးများ',
  'Licence fee revenue': 'လိုင်စင်ကြေးဝင်ငွေ',
  'Licence fees collected': 'ကောက်ခံရလိုင်စင်ကြေး',
  'Licence ≤ 90 days': '၉၀ရက်အတွင်းလိုင်စင်',
  'Licences & money': 'လိုင်စင်နှင့်ငွေကြေး',
  'Licences expiring ≤ 30 days': '၃၀ရက်အတွင်းကုန်မည့်လိုင်စင်',
  'Licensed & active': 'လိုင်စင်ရပြီးလည်ပတ်ဆဲ',
  'Licensed operators': 'လိုင်စင်ရကုမ္ပဏီများ',
  'Licensed since': 'လိုင်စင်ရသည့်ရက်',
  'Licensed vehicles': 'လိုင်စင်ရယာဉ်များ',
  'Licensing overview': 'လိုင်စင်ခြုံငုံသုံးသပ်ချက်',
  'Licensing reports': 'လိုင်စင်အစီရင်ခံစာများ',
  'My applications': 'ကျွန်ုပ်၏လျှောက်လွှာများ',
  'My licences': 'ကျွန်ုပ်၏လိုင်စင်များ',
  'New application': 'လျှောက်လွှာအသစ်',
  'New licence application': 'လိုင်စင်လျှောက်လွှာအသစ်',
  'Open applications': 'ဖွင့်ထားသောလျှောက်လွှာ',
  'Open approval queue': 'အတည်ပြုရန်တန်းစီဖွင့်ရန်',
  'Open officer work queue': 'အရာရှိလုပ်ငန်းတန်းစီဖွင့်ရန်',
  'Open tracker': 'ခြေရာခံဖွင့်ရန်',
  'Open public verification': 'အများပြည်သူစိစစ်မှုဖွင့်ရန်',
  'Fines collected': 'ကောက်ခံရဒဏ်ကြေး',
  'Fines issued': 'ထုတ်ပြန်ပြီးဒဏ်ကြေး',
  'Issue e-fine': 'အီလက်ထရွန်နစ်ဒဏ်ကြေးထုတ်ရန်',
  'Issue a finding': 'တွေ့ရှိချက်ထုတ်ပြန်ရန်',
  'Forward to operator': 'ကုမ္ပဏီထံလွှဲပြောင်းရန်',
  'Has finding': 'တွေ့ရှိချက်ရှိသည်',
  'Fixed departures': 'ပုံသေထွက်ခွာချိန်',
  'Fleet availability': 'ယာဉ်အသင့်ရှိမှု',
  'Fleet map': 'ယာဉ်အစုမြေပုံ',
  'Fleet and disclosure': 'ယာဉ်အစုနှင့်ထုတ်ဖော်မှု',
  Floor: 'အနိမ့်ဆုံးနှုန်း',
  Forecast: 'ခန့်မှန်းချက်',
  Format: 'ပုံစံ',
  Frequency: 'ကြိမ်နှုန်း',
  'Min headway': 'အနည်းဆုံးကားချိန်ခြား',
  'Planned headway': 'စီစဉ်ထားကားချိန်ခြား',
  'Permitted headway': 'ခွင့်ပြုကားချိန်ခြား',
  'Gate events': 'ဂိတ်ဖြစ်ရပ်များ',
  'Gate log': 'ဂိတ်မှတ်တမ်း',
  Geofence: 'ဧရိယာသတ်မှတ်ချက်',
  'GPS IMEI': 'GPS IMEI',
  'Generate report': 'အစီရင်ခံစာထုတ်ရန်',
  'Full solution blueprint': 'စနစ်တစ်ခုလုံးပုံကြမ်း',
  'Help & audit': 'အကူအညီနှင့်စာရင်းစစ်',
  'Home layout & banners': 'ပင်မအပြင်အဆင်နှင့်ဘန်နာ',
  'Home screen blocks': 'ပင်မစာမျက်နှာအပိုင်းများ',
  Hours: 'နာရီ',
  'Hours/wk': 'နာရီ/အပတ်',
  ID: 'အမှတ်',
  Item: 'အရာ',
  Kind: 'အမျိုးအစား',
  Level: 'အဆင့်',
  Layout: 'အပြင်အဆင်',
  'Import GTFS': 'GTFS သွင်းရန်',
  'Impressions billed': 'ငွေတောင်းခံပြီးမြင်တွေ့မှု',
  'Impressions, current period': 'လက်ရှိကာလမြင်တွေ့မှု',
  'In breach': 'ချိုးဖောက်နေ',
  'In pilot': 'စမ်းသပ်အဆင့်',
  'In sandbox': 'စမ်းသပ်ပတ်ဝန်းကျင်',
  'In-app ad slots': 'အက်ပ်တွင်းကြော်ငြာနေရာ',
  'Incidents & SOS': 'ဖြစ်စဉ်နှင့်အရေးပေါ်',
  'Integration monitor': 'ချိတ်ဆက်မှုစောင့်ကြည့်',
  Integrations: 'ချိတ်ဆက်မှုများ',
  'Inventory & rate card': 'နေရာစာရင်းနှင့်နှုန်းထား',
  'Invite a driver': 'ယာဉ်မောင်းဖိတ်ခေါ်ရန်',
  'Invite driver': 'ယာဉ်မောင်းဖိတ်ခေါ်ရန်',
  Invoices: 'ငွေတောင်းခံလွှာများ',
  'Invoices & receipts': 'ငွေတောင်းခံလွှာနှင့်ပြေစာ',
  Outstanding: 'ပေးရန်ကျန်',
  Journey: 'ခရီးစဉ်',
  Journeys: 'ခရီးစဉ်များ',
  'Journeys carried': 'သယ်ဆောင်ပြီးခရီးစဉ်',
  Jurisdiction: 'စီရင်ပိုင်ခွင့်နယ်',
  'Jurisdiction map': 'စီရင်ပိုင်ခွင့်မြေပုံ',
  'Knowledge base': 'အသိပညာစုစည်းမှု',
  Languages: 'ဘာသာစကားများ',
  'Last 14 days': 'နောက်ဆုံး ၁၄ ရက်',
  'Last 30 days': 'နောက်ဆုံး ၃၀ ရက်',
  'Last active': 'နောက်ဆုံးလှုပ်ရှားချိန်',
  'Last change': 'နောက်ဆုံးပြောင်းလဲမှု',
  'Last changed': 'နောက်ဆုံးပြောင်းလဲသည့်ရက်',
  'Last check': 'နောက်ဆုံးစစ်ဆေးချိန်',
  'Last updated': 'နောက်ဆုံးပြင်ဆင်ချိန်',
  Latency: 'နှောင့်နှေးချိန်',
  'Latest alert': 'နောက်ဆုံးသတိပေးချက်',
  'Latest settlement run': 'နောက်ဆုံးရှင်းလင်းမှု',
  'Late penalty': 'နောက်ကျဒဏ်ကြေး',
  Ledger: 'စာရင်းမှတ်တမ်း',
  'Legal pages': 'ဥပဒေစာမျက်နှာများ',
  Lines: 'လမ်းကြောင်းများ',
  'Lines measured': 'တိုင်းတာပြီးလမ်းကြောင်း',
  'Lines at weak end': 'အားနည်းသောလမ်းကြောင်းများ',
  'Live campaigns': 'တိုက်ရိုက်ကြော်ငြာများ',
  'Live map': 'တိုက်ရိုက်မြေပုံ',
  'Live network': 'တိုက်ရိုက်ကွန်ရက်',
  'Live passenger alerts': 'ခရီးသည်သတိပေးချက်များ',
  'Live spend': 'သုံးစွဲပြီးငွေ',
  'Load factor': 'လူစီးနှုန်း',
  'Load factor %': 'လူစီးနှုန်း %',
  'Load factor by line': 'လမ်းကြောင်းအလိုက်လူစီးနှုန်း',
  'Lost property found': 'ပျောက်ဆုံးပစ္စည်းတွေ့ရှိ',
  'Lowest-coverage vehicles': 'လွှမ်းခြုံမှုအနည်းဆုံးယာဉ်',
  'Manage bands': 'အပိုင်းအခြားစီမံရန်',
  'Mandalay Region': 'မန္တလေးတိုင်းဒေသကြီး',
  'Manual fallbacks in force': 'လက်ဖြင့်အစားထိုးမှုသက်ဝင်',
  Marketing: 'ဈေးကွက်ရှာဖွေရေး',
  'Master data': 'အခြေခံအချက်အလက်',
  'Matrix per line': 'လမ်းကြောင်းအလိုက်ဇယား',
  'Measurable lines only': 'တိုင်းတာနိုင်သောလမ်းကြောင်းသာ',
  'Median first response': 'ပထမတုံ့ပြန်ချိန်အလယ်',
  'Median resolution': 'ဖြေရှင်းချိန်အလယ်',
  'Median time to decision': 'ဆုံးဖြတ်ချိန်အလယ်',
  'Medical to': 'ကျန်းမာရေးလက်မှတ်သက်တမ်း',
  Message: 'မက်ဆေ့',
  'Messages sent (30 days)': 'ပို့ပြီးမက်ဆေ့ (၃၀ရက်)',
  Method: 'နည်းလမ်း',
  Mode: 'စနစ်',
  'Ministry pack': 'ဝန်ကြီးဌာနအစီရင်ခံစုစည်းမှု',
  'Ministry reporting pack': 'ဝန်ကြီးဌာနအစီရင်ခံစုစည်းမှု',
  'MMK total': 'MMK စုစုပေါင်း',
  'Model quality': 'မော်ဒယ်အရည်အသွေး',
  Models: 'မော်ဒယ်များ',
  'Models live': 'အသုံးပြုဆဲမော်ဒယ်',
  'Money flow for regulated revenue': 'ထိန်းညှိဝင်ငွေစီးဆင်းမှု',
  Name: 'အမည်',
  'National Coverage Index': 'အမျိုးသားလွှမ်းခြုံမှုညွှန်းကိန်း',
  'National view': 'အမျိုးသားအဆင့်အမြင်',
  'National — all regions': 'အမျိုးသား — တိုင်းဒေသအားလုံး',
  'Net paid': 'အသားတင်ပေးချေပြီး',
  'Net paid out': 'အသားတင်ထုတ်ပေးပြီး',
  'Net settlement': 'အသားတင်ရှင်းလင်းမှု',
  'Net to you': 'သင်ရရှိမည့်အသားတင်',
  'New announcement': 'ကြေညာချက်အသစ်',
  'New article': 'ဆောင်းပါးအသစ်',
  'New key': 'သော့အသစ်',
  'New template': 'ပုံစံအသစ်',
  'Next acknowledgement deadline': 'နောက်လက်ခံရမည့်နောက်ဆုံးချိန်',
  'Next departures': 'နောက်ထွက်ခွာမှုများ',
  'Next tabling': 'နောက်တင်ပြမည့်ရက်',
  'No active SOS': 'လက်ရှိအရေးပေါ်မရှိပါ',
  'No appeals filed': 'အယူခံတင်သွင်းမှုမရှိပါ',
  'No bookings on your services yet': 'သင့်ဝန်ဆောင်မှုတွင်မှာယူမှုမရှိသေးပါ',
  'No content items': 'အကြောင်းအရာမရှိပါ',
  'No findings against your company': 'သင့်ကုမ္ပဏီအပေါ်တွေ့ရှိချက်မရှိပါ',
  'No findings awaiting reply': 'ဖြေကြားရန်တွေ့ရှိချက်မရှိပါ',
  'No findings issued': 'ထုတ်ပြန်ထားသောတွေ့ရှိချက်မရှိပါ',
  'No inspection scheduled': 'စစ်ဆေးမှုစီစဉ်ထားခြင်းမရှိပါ',
  'No licences of this type': 'ဤအမျိုးအစားလိုင်စင်မရှိပါ',
  'No live alerts': 'တိုက်ရိုက်သတိပေးချက်မရှိပါ',
  'No open alerts': 'ဖွင့်ထားသောသတိပေးချက်မရှိပါ',
  'No open applications': 'ဖွင့်ထားသောလျှောက်လွှာမရှိပါ',
  'No open disputes': 'ဖွင့်ထားသောအငြင်းပွားမှုမရှိပါ',
  'No open incidents': 'ဖွင့်ထားသောဖြစ်စဉ်မရှိပါ',
  'No outstanding invoices': 'ပေးရန်ကျန်ငွေတောင်းခံလွှာမရှိပါ',
  'No refused decisions': 'ငြင်းပယ်ထားသောဆုံးဖြတ်ချက်မရှိပါ',
  'No reviews yet': 'သုံးသပ်ချက်မရှိသေးပါ',
  'No upcoming scheduled departures': 'စီစဉ်ထားသောထွက်ခွာမှုမရှိပါ',
  'No work orders': 'လုပ်ငန်းအမိန့်မရှိပါ',
  'No-service window': 'ဝန်ဆောင်မှုမရှိသောအချိန်',
  'Nothing expiring soon': 'မကြာမီကုန်ဆုံးမည့်အရာမရှိပါ',
  'Nothing expiring within 90 days': '၉၀ရက်အတွင်းကုန်ဆုံးမည့်အရာမရှိပါ',
  'Nothing waiting on you': 'သင့်ထံစောင့်နေသောအရာမရှိပါ',
  'Not issued yet': 'မထုတ်ပြန်ရသေးပါ',
  'Non-tax revenue booked': 'အခွန်မဟုတ်သောဝင်ငွေမှတ်တမ်း',
  'Notification delivery': 'အကြောင်းကြားချက်ပေးပို့မှု',
  'Notification templates': 'အကြောင်းကြားချက်ပုံစံများ',
  Object: 'အရာဝတ္ထု',
  'Objectives met': 'ပြည့်မီသောရည်မှန်းချက်',
  'Occupancy %': 'လူပြည့်နှုန်း %',
  'Occupancy by bus': 'ကားအလိုက်လူပြည့်နှုန်း',
  Officer: 'အရာရှိ',
  'Open data': 'ပွင့်လင်းအချက်အလက်',
  'Open findings': 'ဖွင့်ထားသောတွေ့ရှိချက်',
  'Open helpdesk': 'အကူအညီဌာနဖွင့်ရန်',
  'Open incident queue': 'ဖြစ်စဉ်တန်းစီဖွင့်ရန်',
  'Open map': 'မြေပုံဖွင့်ရန်',
  'Open rate': 'ဖွင့်ကြည့်နှုန်း',
  'Open SOS & incidents': 'ဖွင့်ထားသောအရေးပေါ်နှင့်ဖြစ်စဉ်',
  'Open tickets': 'ဖွင့်ထားသောတိုင်ကြားလက်မှတ်',
  'Open work orders': 'ဖွင့်ထားသောလုပ်ငန်းအမိန့်',
  Opened: 'ဖွင့်ပြီး',
  'Operational catalogue': 'လည်ပတ်မှုစာရင်း',
  'Operational report catalogue': 'လည်ပတ်မှုအစီရင်ခံစာစာရင်း',
  'Operations / Dispatcher': 'လည်ပတ်မှု / စေလွှတ်ရေး',
  'Operator league table': 'ကုမ္ပဏီအဆင့်ဇယား',
  'Operator prices': 'ကုမ္ပဏီဈေးနှုန်းများ',
  'Operator share': 'ကုမ္ပဏီဝေစု',
  Operators: 'ကုမ္ပဏီများ',
  'Operators serving': 'ဝန်ဆောင်မှုပေးသောကုမ္ပဏီ',
  'Operators, fleet & drivers': 'ကုမ္ပဏီ၊ ယာဉ်နှင့်ယာဉ်မောင်း',
  Organisation: 'အဖွဲ့အစည်း',
  'Origin–destination pairs, today': 'ယနေ့ထွက်ခွာ–ဆိုက်ရောက်တွဲများ',
  'Owned by': 'ပိုင်ဆိုင်သူ',
  Owner: 'ပိုင်ရှင်',
  'Owning office': 'တာဝန်ခံရုံး',
  'P1 (SOS)': 'P1 (အရေးပေါ်)',
  Page: 'စာမျက်နှာ',
  'Paid this register': 'ဤမှတ်ပုံတင်တွင်ပေးချေပြီး',
  Party: 'သက်ဆိုင်သူ',
  'Pass holders': 'ပါမစ်ကိုင်ဆောင်သူ',
  'Passenger manifest': 'ခရီးသည်စာရင်း',
  'Passengers expected': 'မျှော်မှန်းခရီးသည်',
  'Password only': 'စကားဝှက်သာ',
  Pay: 'ပေးချေရန်',
  'Pay now': 'ယခုပေးချေရန်',
  'Payment fee': 'ငွေပေးချေမှုကြေး',
  'Payout history': 'ငွေထုတ်ပေးမှုမှတ်တမ်း',
  'Peak today': 'ယနေ့အမြင့်ဆုံး',
  'People on site': 'နေရာတွင်ရှိသူဦးရေ',
  'Performance against published objectives': 'ကြေညာထားရည်မှန်းချက်နှင့်စွမ်းဆောင်ရည်',
  Period: 'ကာလ',
  'Permission matrix': 'ခွင့်ပြုချက်ဇယား',
  Permissions: 'ခွင့်ပြုချက်များ',
  'Permit validation': 'ခွင့်ပြုမိန့်စိစစ်မှု',
  'Permits held': 'ကိုင်ဆောင်ထားခွင့်ပြုမိန့်',
  'Permits needing attention': 'အာရုံစိုက်ရန်လိုသောခွင့်ပြုမိန့်',
  Phase: 'အဆင့်',
  'Physical inspection (ramp check)': 'လက်တွေ့စစ်ဆေးမှု',
  Plate: 'ကားနံပါတ်',
  'Platform admin': 'ပလက်ဖောင်းစီမံခန့်ခွဲမှု',
  'Platform fee': 'ပလက်ဖောင်းကြေး',
  'Platform sales and levy': 'ပလက်ဖောင်းအရောင်းနှင့်အခွန်',

  // ------------------------------------------------------------- batch 3
  PNR: 'မှာယူမှုကုဒ်',
  'PO Admin': 'ကုမ္ပဏီစီမံခန့်ခွဲသူ',
  POs: 'ကုမ္ပဏီများ',
  'Police e-ticketing link': 'ရဲတပ်ဖွဲ့ဒဏ်ကြေးချိတ်ဆက်မှု',
  'Policy KPIs met': 'ပြည့်မီသောမူဝါဒ KPI',
  'Policy KPIs vs targets': 'မူဝါဒ KPI နှင့်ပန်းတိုင်',
  'Population %': 'လူဦးရေ %',
  'Population within 400 m': 'မီတာ ၄၀၀ အတွင်းလူဦးရေ',
  'Position in band': 'အပိုင်းအခြားအတွင်းအနေအထား',
  Pri: 'ဦးစားပေး',
  'Priced outside the band': 'အပိုင်းအခြားပြင်ပဈေးနှုန်း',
  Print: 'ပုံနှိပ်ရန်',
  Priority: 'ဦးစားပေး',
  'Prohibited categories': 'တားမြစ်အမျိုးအစားများ',
  'Promo codes & passes': 'ပရိုမိုကုဒ်နှင့်ပါမစ်',
  'Proof required': 'သက်သေလိုအပ်',
  Provider: 'ဝန်ဆောင်မှုပေးသူ',
  'Public board': 'အများပြည်သူပြဘုတ်',
  'Public information': 'အများပြည်သူသတင်းအချက်အလက်',
  'CMS · Content & messaging': 'CMS · အကြောင်းအရာနှင့်မက်ဆေ့',
  'CMS · Advertising': 'CMS · ကြော်ငြာ',
  'Public satisfaction': 'ပြည်သူ့စိတ်ကျေနပ်မှု',
  'Public verification': 'အများပြည်သူစိစစ်မှု',
  Publish: 'ထုတ်ပြန်ရန်',
  'Publish layout': 'အပြင်အဆင်ထုတ်ပြန်ရန်',
  'Publish reply': 'အဖြေထုတ်ပြန်ရန်',
  'Publish roster': 'တာဝန်ဇယားထုတ်ပြန်ရန်',
  Purchased: 'ဝယ်ယူပြီး',
  'Push notification': 'ပူရှ်အကြောင်းကြားချက်',
  Qty: 'အရေအတွက်',
  'Quality KPIs': 'အရည်အသွေး KPI များ',
  'Queue is clear': 'တန်းစီရှင်းလင်းပြီ',
  'Raise a support ticket': 'အကူအညီတောင်းခံရန်',
  'Raise a ticket': 'တိုင်ကြားလက်မှတ်ဖွင့်ရန်',
  'Raise work order': 'လုပ်ငန်းအမိန့်ထုတ်ရန်',
  Raised: 'ဖွင့်ခဲ့သည်',
  'Raised by': 'ဖွင့်သူ',
  'Ramp checks': 'လက်တွေ့စစ်ဆေးမှုများ',
  'Ramp checks scheduled': 'စီစဉ်ထားစစ်ဆေးမှု',
  'Rate (CPM)': 'နှုန်း (CPM)',
  'Rate card notes': 'နှုန်းထားမှတ်ချက်',
  'Rate limits': 'နှုန်းကန့်သတ်ချက်',
  'Rating distribution': 'အဆင့်သတ်မှတ်ချက်ဖြန့်ဝေမှု',
  'Reachable audience': 'ရောက်ရှိနိုင်သောပရိသတ်',
  'Reason for last change': 'နောက်ဆုံးပြောင်းလဲရခြင်းအကြောင်းရင်း',
  'Reason missing': 'အကြောင်းပြချက်မပါ',
  'Reasons not recorded': 'အကြောင်းပြချက်မမှတ်တမ်းတင်ထား',
  'Recent broadcasts': 'မကြာသေးမီပို့ချက်များ',
  'Recent deliveries': 'မကြာသေးမီပေးပို့မှုများ',
  'Recent reviews': 'မကြာသေးမီသုံးသပ်ချက်',
  Recipient: 'လက်ခံသူ',
  'Reconciled daily': 'နေ့စဉ်ညှိနှိုင်းပြီး',
  Reconciliation: 'စာရင်းညှိနှိုင်းမှု',
  'Reconciliation exceptions': 'စာရင်းညှိနှိုင်းမှုခြွင်းချက်',
  Records: 'မှတ်တမ်းများ',
  Reference: 'ကိုးကားနံပါတ်',
  Refund: 'ငွေပြန်အမ်းမှု',
  'Refund disputes': 'ငွေပြန်အမ်းမှုအငြင်းပွားမှု',
  'Refund policy in force': 'သက်ဝင်နေသောငွေပြန်အမ်းမူဝါဒ',
  'Refund timeline': 'ငွေပြန်အမ်းမှုအချိန်ဇယား',
  'Refunds & reschedule': 'ငွေပြန်အမ်းခြင်းနှင့်ရက်ပြောင်းခြင်း',
  Region: 'တိုင်းဒေသ',
  'Region league table': 'တိုင်းဒေသအဆင့်ဇယား',
  'Regions live': 'လည်ပတ်နေသောတိုင်းဒေသ',
  'Registered details': 'မှတ်ပုံတင်အချက်အလက်',
  'Registry checks': 'မှတ်ပုံတင်စစ်ဆေးမှု',
  'Regular bus': 'ပုံမှန်ဘတ်စ်ကား',
  'Regulated revenue (month)': 'ထိန်းညှိဝင်ငွေ (လ)',
  'Reject application': 'လျှောက်လွှာငြင်းပယ်ရန်',
  'Rejected scans': 'ငြင်းပယ်ခံစကင်များ',
  Renewals: 'သက်တမ်းတိုးမှုများ',
  'Replies published': 'ထုတ်ပြန်ပြီးအဖြေများ',
  Reply: 'ဖြေကြားရန်',
  'Reply to a passenger': 'ခရီးသည်ကိုဖြေကြားရန်',
  Report: 'အစီရင်ခံစာ',
  Reported: 'တိုင်ကြားပြီး',
  'Reported today': 'ယနေ့တိုင်ကြားမှု',
  'Reporting scope': 'အစီရင်ခံနယ်ပယ်',
  'Request account change': 'အကောင့်ပြောင်းလဲရန်တောင်းဆိုမှု',
  'Request revision': 'ပြင်ဆင်ရန်တောင်းဆိုမှု',
  'Request variant': 'ပုံစံကွဲတောင်းဆိုမှု',
  Requirements: 'လိုအပ်ချက်များ',
  Reschedule: 'ရက်ပြောင်းရန်',
  'Reseed demo data': 'စမ်းသပ်အချက်အလက်ပြန်ထည့်ရန်',
  'Resolve reconciliation exception': 'စာရင်းညှိနှိုင်းခြွင်းချက်ဖြေရှင်းရန်',
  'Resolve with reason': 'အကြောင်းပြချက်ဖြင့်ဖြေရှင်းရန်',
  Resolved: 'ဖြေရှင်းပြီး',
  'Respond to the authority': 'အာဏာပိုင်ထံတုံ့ပြန်ရန်',
  'Respond with reason': 'အကြောင်းပြချက်ဖြင့်တုံ့ပြန်ရန်',
  'Resubmit corrected documents': 'ပြင်ဆင်ပြီးစာရွက်ပြန်တင်ရန်',
  Result: 'ရလဒ်',
  'Revenue (booked)': 'ဝင်ငွေ (မှာယူပြီး)',
  'Revenue split': 'ဝင်ငွေခွဲဝေမှု',
  'Review and submit': 'သုံးသပ်ပြီးတင်သွင်းရန်',
  Roles: 'ရာထူးများ',
  'Route permits': 'လမ်းကြောင်းခွင့်ပြုမိန့်',
  'Route price floors and ceilings': 'လမ်းကြောင်းဈေးနှုန်းအနိမ့်ဆုံးနှင့်အမြင့်ဆုံး',
  'Routes banded': 'အပိုင်းအခြားသတ်မှတ်ပြီးလမ်းကြောင်း',
  Ruled: 'ဆုံးဖြတ်ပြီး',
  'Rules that always apply': 'အမြဲသက်ဝင်သောစည်းမျဉ်း',
  Runs: 'ခရီးစဉ်များ',
  Sales: 'အရောင်း',
  'Sales by channel': 'လမ်းကြောင်းအလိုက်အရောင်း',
  Sanction: 'အရေးယူမှု',
  Sanctions: 'အရေးယူမှုများ',
  'Sanctions active': 'သက်ဝင်အရေးယူမှု',
  Sandbox: 'စမ်းသပ်ပတ်ဝန်းကျင်',
  'Save draft': 'မူကြမ်းသိမ်းရန်',
  'Save timetable': 'အချိန်ဇယားသိမ်းရန်',
  'Save version': 'ဗားရှင်းသိမ်းရန်',
  'Save webhook': 'webhook သိမ်းရန်',
  Scan: 'စကင်ဖတ်ရန်',
  'Scan log': 'စကင်မှတ်တမ်း',
  'Scan ticket': 'လက်မှတ်စကင်ဖတ်ရန်',
  'Schedule inspection': 'စစ်ဆေးမှုစီစဉ်ရန်',
  'Scheduled deliveries': 'စီစဉ်ထားပေးပို့မှုများ',
  'Scheduled services only': 'စီစဉ်ထားဝန်ဆောင်မှုသာ',
  'Search bar': 'ရှာဖွေရေးဘား',
  Searches: 'ရှာဖွေမှုများ',
  'Seat layout': 'ထိုင်ခုံအပြင်အဆင်',
  'Seat-layout editor': 'ထိုင်ခုံအပြင်အဆင်တည်းဖြတ်ကိရိယာ',
  Seats: 'ထိုင်ခုံများ',
  Segment: 'အပိုင်း',
  'Sell ticket': 'လက်မှတ်ရောင်းရန်',
  'Selling now': 'ယခုရောင်းချနေ',
  Send: 'ပို့ရန်',
  'Send and resolve': 'ပို့ပြီးဖြေရှင်းရန်',
  'Send invite': 'ဖိတ်ကြားချက်ပို့ရန်',
  'Send reply and resolve': 'အဖြေပို့ပြီးဖြေရှင်းရန်',
  'Send to approver': 'အတည်ပြုသူထံပို့ရန်',
  'Sent by': 'ပို့သူ',
  'Sent this week': 'ဤအပတ်ပို့ပြီး',
  Service: 'ဝန်ဆောင်မှု',
  'Service alert strip': 'ဝန်ဆောင်မှုသတိပေးအစင်း',
  'Service day': 'ဝန်ဆောင်မှုနေ့',
  'Service delivery today': 'ယနေ့ဝန်ဆောင်မှုပေးအပ်မှု',
  'Service levels': 'ဝန်ဆောင်မှုအဆင့်များ',
  'Service on time': 'အချိန်မှန်ဝန်ဆောင်မှု',
  'Service standards per class': 'အဆင့်အလိုက်ဝန်ဆောင်မှုစံနှုန်း',
  'Set band': 'အပိုင်းအခြားသတ်မှတ်ရန်',
  'Settlement bank account': 'ရှင်းလင်းရေးဘဏ်အကောင့်',
  Severity: 'ပြင်းထန်မှုအဆင့်',
  Share: 'မျှဝေရန်',
  'Shift assignments': 'အလုပ်ဆိုင်းတာဝန်ခွဲဝေမှု',
  Size: 'အရွယ်အစား',
  'SLA overdue': 'SLA ကျော်လွန်',
  Slack: 'ခွင့်ပြုအကွာအဝေး',
  Slots: 'နေရာများ',
  Sold: 'ရောင်းပြီး',
  Source: 'ရင်းမြစ်',
  'Speed & occupancy': 'အမြန်နှုန်းနှင့်လူပြည့်နှုန်း',
  Spend: 'သုံးစွဲငွေ',
  'Split rules in force': 'သက်ဝင်ခွဲဝေမှုစည်းမျဉ်း',
  Stop: 'မှတ်တိုင်',
  Stops: 'မှတ်တိုင်များ',
  Student: 'ကျောင်းသား',
  'Sub-tenants': 'လက်အောက်ခံအသုံးပြုသူများ',
  'Submit and issue invoice': 'တင်သွင်းပြီးငွေတောင်းခံလွှာထုတ်ရန်',
  'Submit fare change': 'စီးခပြောင်းလဲမှုတင်သွင်းရန်',
  'Submit for approval': 'အတည်ပြုရန်တင်သွင်းရန်',
  'Submit request': 'တောင်းဆိုချက်တင်သွင်းရန်',
  Submitted: 'တင်သွင်းပြီး',
  Suspended: 'ရပ်ဆိုင်းထား',
  'System health': 'စနစ်ကျန်းမာရေး',
  Take: 'ရယူငွေ',
  'Telematics devices': 'တယ်လီမက်တစ်ကိရိယာများ',
  Template: 'ပုံစံ',
  Tenant: 'အသုံးပြုအဖွဲ့',
  Tenants: 'အသုံးပြုအဖွဲ့များ',
  Terminal: 'ဂိတ်',
  'Terminal overview': 'ဂိတ်ခြုံငုံသုံးသပ်ချက်',
  'Terminals in your scope': 'သင့်နယ်ပယ်အတွင်းဂိတ်များ',
  'This week vs last': 'ဤအပတ်နှင့်ယခင်အပတ်',
  'Three-way reconciliation': 'သုံးဖက်စာရင်းညှိနှိုင်းမှု',
  'Thresholds & policy': 'ကန့်သတ်ချက်နှင့်မူဝါဒ',
  'Thresholds in force': 'သက်ဝင်ကန့်သတ်ချက်',
  'Throughput by hour': 'နာရီအလိုက်လုပ်ဆောင်နိုင်မှု',
  'Ticket code': 'လက်မှတ်ကုဒ်',
  'Ticket ID': 'လက်မှတ်အမှတ်',
  Ticketing: 'လက်မှတ်စနစ်',
  Tickets: 'လက်မှတ်များ',
  'Tickets today': 'ယနေ့လက်မှတ်',
  Time: 'အချိန်',
  Timeline: 'အချိန်ဇယား',
  'Timetable editor': 'အချိန်ဇယားတည်းဖြတ်ကိရိယာ',
  Timing: 'အချိန်ကိုက်ညီမှု',
  Title: 'ခေါင်းစဉ်',
  'Today at a glance': 'ယနေ့အကျဉ်းချုပ်',
  "Today's service day": 'ယနေ့ဝန်ဆောင်မှုနေ့',
  'Transition log': 'အခြေအနေပြောင်းလဲမှုမှတ်တမ်း',
  Transmitting: 'အချက်ပြနေ',
  Treasury: 'ဘဏ္ဍာတော်',
  'Trip replay': 'ခရီးစဉ်ပြန်ကြည့်ရန်',
  Trips: 'ခရီးစဉ်များ',
  'Trips measured today': 'ယနေ့တိုင်းတာခရီးစဉ်',
  'Trips to crew': 'အမှုထမ်းသို့ခရီးစဉ်',
  'Trips today': 'ယနေ့ခရီးစဉ်',
  'Trunk corridors': 'ပင်မလမ်းကြောင်းများ',
  Unassigned: 'မသတ်မှတ်ရသေး',
  Unpaid: 'မပေးချေရသေး',
  'Unpaid invoices': 'မပေးချေရသေးငွေတောင်းခံလွှာ',
  'Unserved demand': 'မဖြည့်ဆည်းရသေးဝယ်လိုအား',
  'Unserved searches': 'ရလဒ်မရှိရှာဖွေမှု',
  Until: 'အထိ',
  'Upcoming departures': 'လာမည့်ထွက်ခွာမှုများ',
  Uphold: 'အတည်ပြုရန်',
  'Upload document': 'စာရွက်စာတမ်းတင်ရန်',
  Uploaded: 'တင်ပြီး',
  'Use case': 'အသုံးပြုပုံ',
  'Used for': 'အသုံးပြုရန်',
  'Users & roles': 'အသုံးပြုသူနှင့်ရာထူး',
  'Valid permits': 'သက်တမ်းရှိခွင့်ပြုမိန့်',
  Vehicle: 'ယာဉ်',
  'Vehicle not found': 'ယာဉ်မတွေ့ပါ',
  'Vehicle record': 'ယာဉ်မှတ်တမ်း',
  'Vehicles blocked': 'ပိတ်ပင်ထားယာဉ်',
  'Vehicles held': 'ထိန်းထားယာဉ်',
  'Vehicles in service': 'ဝန်ဆောင်မှုပေးနေယာဉ်',
  'Vehicles required': 'လိုအပ်ယာဉ်အရေအတွက်',
  'Vehicles tracked today': 'ယနေ့ခြေရာခံယာဉ်',
  Ver: 'ဗားရှင်း',
  Verification: 'စိစစ်မှု',
  'Verification checklist': 'စိစစ်မှုစာရင်း',
  Verify: 'စိစစ်ရန်',
  'Verify permit': 'ခွင့်ပြုမိန့်စိစစ်ရန်',
  'Verify response': 'တုံ့ပြန်မှုစိစစ်ရန်',
  'Verify, acknowledge or forward': 'စိစစ်၊ လက်ခံ သို့မဟုတ် လွှဲပြောင်းရန်',
  Version: 'ဗားရှင်း',
  Viewer: 'ကြည့်ရှုသူ',
  Violations: 'ချိုးဖောက်မှုများ',
  Wait: 'စောင့်ဆိုင်းချိန်',
  'Wait P50': 'စောင့်ဆိုင်းချိန် P50',
  'Wait P90': 'စောင့်ဆိုင်းချိန် P90',
  'Wallet & emergency shortcuts': 'ပိုက်ဆံအိတ်နှင့်အရေးပေါ်ဖြတ်လမ်း',
  Webhooks: 'Webhooks',
  'What are you applying for?': 'မည်သည့်အရာလျှောက်ထားမည်နည်း။',
  'What each level sees': 'အဆင့်တစ်ခုချင်းမြင်ရမှု',
  'What each role may do': 'ရာထူးတစ်ခုချင်းလုပ်ပိုင်ခွင့်',
  'What it contains': 'ပါဝင်သည့်အကြောင်းအရာ',
  'Where complaints come from': 'တိုင်ကြားချက်ရင်းမြစ်',
  'Where it appears': 'ပေါ်မည့်နေရာ',
  'Where regulated revenue comes from': 'ထိန်းညှိဝင်ငွေရင်းမြစ်',
  'Where the money goes': 'ငွေသွားရာလမ်းကြောင်း',
  'Why it fails': 'မအောင်မြင်ရခြင်းအကြောင်းရင်း',
  'Windscreen QR': 'ကားမှန်ကပ် QR',
  'With a written reason': 'စာဖြင့်အကြောင်းပြချက်ဖြင့်',
  Withdraw: 'ရုပ်သိမ်းရန်',
  'Without owner': 'ပိုင်ရှင်မရှိ',
  'Work order': 'လုပ်ငန်းအမိန့်',
  'Work orders and defects': 'လုပ်ငန်းအမိန့်နှင့်ချို့ယွင်းချက်',
  'Worst deviations today': 'ယနေ့အဆိုးဆုံးသွေဖည်မှု',
  'Written reason': 'စာဖြင့်အကြောင်းပြချက်',
  'Yangon Region': 'ရန်ကုန်တိုင်းဒေသကြီး',
  "Yesterday's settlement": 'မနေ့ကရှင်းလင်းမှု',
  'Your fleet, live': 'သင့်ယာဉ်အစု၊ တိုက်ရိုက်',
  'Your network': 'သင့်ကွန်ရက်',
  'Your vehicles only': 'သင့်ယာဉ်များသာ',
  'Arrivals at nearest stop': 'အနီးဆုံးမှတ်တိုင်ရောက်ရှိချိန်',
  'Cannot start a shift': 'အလုပ်ဆင်းမရနိုင်ပါ',
  'Conversation path': 'စကားပြောလမ်းကြောင်း',
  'Departures (14d)': 'ထွက်ခွာမှု (၁၄ရက်)',
  digital: 'ဒစ်ဂျစ်တယ်',
  'KPI dictionary': 'KPI အဓိပ္ပာယ်ဖွင့်ဆိုချက်',
  'OCR expiry': 'OCR ဖတ်ယူသက်တမ်း',
  'On-time target': 'အချိန်မှန်ပန်းတိုင်',
  'Of comfortable capacity': 'သက်တောင့်သက်သာဆံ့မှု၏',
  'Passengers at a terminal': 'ဂိတ်တွင်ခရီးသည်များ',
  'Passengers on a route': 'လမ်းကြောင်းပေါ်ခရီးသည်များ',
  'Counterparty (to be confirmed)': 'သက်ဆိုင်သူ (အတည်ပြုရန်)',
  'Geofence, speeding and harsh events': 'ဧရိယာ၊ အရှိန်လွန်နှင့်ကြမ်းတမ်းမောင်းနှင်မှု',
  'Highest unserved demand first': 'မဖြည့်ဆည်းရသေးဝယ်လိုအားများသည်မှစ၍',
  'Only your permitted lines are drawn': 'သင်ခွင့်ပြုထားသောလမ်းကြောင်းများသာပြသည်',
  'Ordered by acknowledgement deadline': 'လက်ခံရမည့်နောက်ဆုံးချိန်အလိုက်စီထား',
  'Every licensed vehicle in this region': 'ဤတိုင်းဒေသအတွင်းလိုင်စင်ရယာဉ်အားလုံး',
  'Failed searches and why': 'ရလဒ်မရှိရှာဖွေမှုနှင့်အကြောင်းရင်း',
  'Last change on each route': 'လမ်းကြောင်းအလိုက်နောက်ဆုံးပြောင်းလဲမှု',
  'Levy and licence fees, 14 days': 'အခွန်နှင့်လိုင်စင်ကြေး၊ ၁၄ရက်',
  'Non-tax revenue, last 14 days': 'အခွန်မဟုတ်ဝင်ငွေ၊ နောက်ဆုံး ၁၄ရက်',
  'Last 30 days, by channel': 'နောက်ဆုံး ၃၀ရက်၊ လမ်းကြောင်းအလိုက်',
  'Occupancy against comfortable capacity': 'သက်တောင့်သက်သာဆံ့မှုနှင့်လူပြည့်နှုန်း',
  'Order as the passenger will see it': 'ခရီးသည်မြင်ရမည့်အစီအစဉ်',
  'Tickets and levy, 14 days': 'လက်မှတ်နှင့်အခွန်၊ ၁၄ရက်',
  'Seats sold ÷ seats offered': 'ရောင်းပြီးထိုင်ခုံ ÷ ကမ်းလှမ်းထိုင်ခုံ',
  'Vehicles transmitting ÷ vehicles expected': 'အချက်ပြယာဉ် ÷ မျှော်မှန်းယာဉ်',
  'Withheld under k-anonymity': 'k-anonymity အရထိန်းချုပ်ထားသည်',
  'Reason and version, for the audit trail': 'စာရင်းစစ်အတွက်အကြောင်းပြချက်နှင့်ဗားရှင်း',
  'Walking reach of the network': 'ကွန်ရက်သို့လမ်းလျှောက်ရောက်ရှိနိုင်မှု',
  'Three-way: provider, ledger, bank': 'သုံးဖက်— ဝန်ဆောင်မှုပေးသူ၊ စာရင်း၊ ဘဏ်',
  'T+1 payouts per operator': 'ကုမ္ပဏီအလိုက် T+1 ငွေထုတ်ပေးမှု',
  'Where your T+1 payout is credited': 'သင့် T+1 ငွေထည့်သွင်းမည့်နေရာ',
  'When the request is made': 'တောင်းဆိုချိန်',
  'Published to passengers before payment': 'ငွေမပေးမီခရီးသည်များအားကြေညာထား',
  'Production — reservations system': 'လက်တွေ့အသုံးပြု — ကြိုတင်မှာယူမှုစနစ်',
  'In-bus screen — your own buses': 'ကားတွင်းဖန်သားပြင် — သင့်ကိုယ်ပိုင်ကားများ',
  'What the ministry asks this office for': 'ဝန်ကြီးဌာနကဤရုံးထံတောင်းဆိုချက်',
  'The invitee enrols 2FA before first sign-in.':
    'ဖိတ်ခေါ်ခံရသူသည် ပထမအကြိမ်မဝင်မီ နှစ်ဆင့်အတည်ပြုမှုကို စာရင်းသွင်းရမည်။',
  'Gross value and journey count, last 14 days': 'စုစုပေါင်းတန်ဖိုးနှင့်ခရီးစဉ်အရေအတွက်၊ နောက်ဆုံး ၁၄ရက်',
  'Last 14 days, your share of platform sales': 'နောက်ဆုံး ၁၄ရက်၊ ပလက်ဖောင်းအရောင်းမှသင့်ဝေစု',
  'Pick a bus and a place to extend it to': 'ကားတစ်စီးနှင့်တိုးချဲ့မည့်နေရာကိုရွေးပါ',
  'Point the gate reader at the passenger QR': 'ဂိတ်စကင်နာကိုခရီးသည် QR ဆီချိန်ပါ',
  'Issued on approval, signed and verifiable': 'အတည်ပြုချိန်တွင်ထုတ်ပေးပြီး လက်မှတ်ရေးထိုးကာစိစစ်နိုင်သည်',
  'Issued automatically from the versioned fee schedule': 'ဗားရှင်းသတ်မှတ်အခကြေးငွေဇယားမှအလိုအလျောက်ထုတ်ပေးသည်',
  'Advisory overlay — an officer still decides': 'အကြံပြုချက်သာ — အရာရှိကသာဆုံးဖြတ်သည်',
  'Applied to every assistant on every turn': 'အကူအညီပေးစနစ်တိုင်း၏အဆင့်တိုင်းတွင်သက်ဝင်သည်',
  'Identical for all three assistants': 'အကူအညီပေးစနစ်သုံးခုလုံးအတွက်တူညီသည်',
  'How each model reaches a screen': 'မော်ဒယ်တစ်ခုချင်းဖန်သားပြင်သို့ရောက်ရှိပုံ',
  'How fees reach the treasury': 'အခကြေးငွေဘဏ္ဍာတော်သို့ရောက်ရှိပုံ',
  'How the band is enforced': 'အပိုင်းအခြားအတည်ပြုကျင့်သုံးပုံ',
  'Every figure carries its source label': 'ကိန်းဂဏန်းတိုင်းတွင်ရင်းမြစ်အညွှန်းပါရှိသည်',
  'Confirmation offer — after payment': 'အတည်ပြုကမ်းလှမ်းချက် — ငွေပေးပြီးနောက်',
  'E-ticket footer — ticket screen and PDF': 'လက်မှတ်အောက်ခြေ — လက်မှတ်ဖန်သားပြင်နှင့် PDF',
  'Against the non-functional requirements': 'လုပ်ဆောင်ချက်မဟုတ်သောလိုအပ်ချက်များနှင့်ယှဉ်၍',
  'What if we extended a line?': 'လမ်းကြောင်းတစ်ခုတိုးချဲ့လျှင်ဘာဖြစ်မလဲ။',

  // ------------------------------------------- status pills and progress
  'In review': 'သုံးသပ်ဆဲ',
  Acknowledged: 'လက်ခံပြီး',
  'In progress': 'ဆောင်ရွက်ဆဲ',
  Running: 'ပြေးဆွဲနေ',
  Scheduled: 'စီစဉ်ထား',
  Booked: 'မှာယူပြီး',
  New: 'အသစ်',
  'Awaiting payment': 'ငွေပေးရန်စောင့်',
  'Revision requested': 'ပြင်ဆင်ရန်တောင်းဆို',
  Forwarded: 'လွှဲပြောင်းပြီး',
  'Operator responded': 'ကုမ္ပဏီတုံ့ပြန်ပြီး',
  Disputed: 'အငြင်းပွားနေ',
  Degraded: 'ချို့ယွင်းနေ',
  Draft: 'မူကြမ်း',
  Rejected: 'ငြင်းပယ်ပြီး',
  Failed: 'မအောင်မြင်ပါ',
  Down: 'ရပ်ဆိုင်းနေ',
  Upheld: 'အတည်ပြုပြီး',
  Overdue: 'သတ်မှတ်ချိန်ကျော်',
  Used: 'သုံးပြီး',
  Expired: 'သက်တမ်းကုန်',
  Withdrawn: 'ရုပ်သိမ်းပြီး',
  Verified: 'စိစစ်ပြီး',
  Published: 'ထုတ်ပြန်ပြီး',
  Balanced: 'ညီမျှ',
  Completed: 'ပြီးစီး',
  'Off service': 'ဝန်ဆောင်မှုမရှိ',
  'Headway / on-time adherence': 'ကားချိန်ခြား / အချိန်မှန်မှု',
  'Fleet availability': 'ယာဉ်အသင့်ရှိမှု',
  'Drivers licensed and available': 'လိုင်စင်ရပြီးအသင့်ရှိယာဉ်မောင်း',
  'Vehicles transmitting': 'အချက်ပြနေသောယာဉ်',
  'Trips completed': 'ပြီးစီးခရီးစဉ်',
  'Trips running': 'ပြေးဆွဲဆဲခရီးစဉ်',
  'Average delay': 'ပျမ်းမျှနောက်ကျချိန်',
  'Licences expiring in 30 days': '၃၀ရက်အတွင်းကုန်မည့်လိုင်စင်',
  'Drivers licensed and active': 'လိုင်စင်ရပြီးလှုပ်ရှားဆဲယာဉ်မောင်း',
  Full: 'ပြည့်',
  Partial: 'တစ်ပိုင်းတစ်စ',
  Low: 'နည်း',

  // ------------------------------------------------- inline field labels
  'Additional vehicles needed': 'ထပ်လိုအပ်ယာဉ်အရေအတွက်',
  Ads: 'ကြော်ငြာ',
  'AI / ML & chatbot': 'AI / ML နှင့်ချက်ဘော့',
  Alcohol: 'အရက်စစ်ဆေးမှု',
  'Analytics & reporting': 'ခွဲခြမ်းစိတ်ဖြာမှုနှင့်အစီရင်ခံမှု',
  'API gateway': 'API ဂိတ်ဝေး',
  Approver: 'အတည်ပြုသူ',
  'Assigned line': 'တာဝန်ကျလမ်းကြောင်း',
  'Assigned officer': 'တာဝန်ကျအရာရှိ',
  'Authority acknowledged': 'အာဏာပိုင်လက်ခံပြီး',
  'Automatic passenger counter': 'အလိုအလျောက်ခရီးသည်ရေတွက်စက်',
  'Booking & order': 'မှာယူမှုနှင့်အော်ဒါ',
  'Census floor': 'စာရင်းကောက်အနိမ့်ဆုံးနှုန်း',
  Chassis: 'ချက်စစ်နံပါတ်',
  'Citizen App': 'ပြည်သူ့အက်ပ်',
  'Citizen app availability': 'ပြည်သူ့အက်ပ်အသုံးပြုနိုင်မှု',
  CTR: 'နှိပ်မှုနှုန်း',
  'Daily operations': 'နေ့စဉ်လည်ပတ်မှု',
  'Device IMEI': 'ကိရိယာ IMEI',
  'Documents attached': 'ပူးတွဲစာရွက်စာတမ်း',
  'Executive summary': 'အနှစ်ချုပ်',
  Experience: 'အတွေ့အကြုံ',
  'Extra population reached': 'ထပ်ရောက်ရှိလူဦးရေ',
  'FAQs and help articles': 'မေးခွန်းများနှင့်အကူအညီဆောင်းပါး',
  'Fare engine': 'စီးခတွက်ချက်စနစ်',
  'Fee basis': 'အခကြေးငွေတွက်ပုံ',
  'Fee schedule version': 'အခကြေးငွေဇယားဗားရှင်း',
  'Full disclosure floor': 'အပြည့်အဝထုတ်ဖော်အနိမ့်ဆုံးနှုန်း',
  'GPS tracker': 'GPS ခြေရာခံကိရိယာ',
  'IAM / SSO': 'IAM / SSO',
  'Indicative floor': 'ညွှန်ပြအနိမ့်ဆုံးနှုန်း',
  Insurance: 'အာမခံ',
  'Invoice issued on submission': 'တင်သွင်းချိန်ငွေတောင်းခံလွှာထုတ်',
  'k-anonymity': 'k-anonymity',
  'Levy (14 days)': 'အခွန် (၁၄ရက်)',
  'Licence fees paid': 'ပေးချေပြီးလိုင်စင်ကြေး',
  Licensing: 'လိုင်စင်',
  'Licensing workflow': 'လိုင်စင်လုပ်ငန်းစဉ်',
  'MDVR dashcam': 'MDVR ကင်မရာ',
  'Minimum headway': 'အနည်းဆုံးကားချိန်ခြား',
  'Network & fleet': 'ကွန်ရက်နှင့်ယာဉ်အစု',
  'Next stop': 'နောက်မှတ်တိုင်',
  Notification: 'အကြောင်းကြားချက်',
  'Notification delivery rate': 'အကြောင်းကြားချက်ပေးပို့နှုန်း',
  Occupancy: 'လူပြည့်နှုန်း',
  Odometer: 'ခရီးမိုင်',
  'Officer assistant': 'အရာရှိအကူအညီပေးစနစ်',
  'Operations summary': 'လည်ပတ်မှုအနှစ်ချုပ်',
  'Operator assistant': 'ကုမ္ပဏီအကူအညီပေးစနစ်',
  'Panic button': 'အရေးပေါ်ခလုတ်',
  'Payment & revenue': 'ငွေပေးချေမှုနှင့်ဝင်ငွေ',
  'Payment method': 'ငွေပေးချေမှုနည်းလမ်း',
  'Payment orchestration': 'ငွေပေးချေမှုစီမံစနစ်',
  'Permit expiry': 'ခွင့်ပြုမိန့်သက်တမ်း',
  'Permitted hours': 'ခွင့်ပြုလည်ပတ်ချိန်',
  'Primary depot': 'အဓိကကားဂိတ်ရုံ',
  'Prominent warning floor': 'ထင်ရှားသောသတိပေးအနိမ့်ဆုံးနှုန်း',
  Push: 'ပူရှ်',
  'Push (FCM / APNs)': 'ပူရှ် (FCM / APNs)',
  Quantity: 'အရေအတွက်',
  'Real-time & ETA': 'အချိန်နှင့်တပြေးညီနှင့်ရောက်ချိန်',
  'Receipt number': 'ပြေစာနံပါတ်',
  'Regular driver': 'ပုံမှန်ယာဉ်မောင်း',
  'Regulated revenue today': 'ယနေ့ထိန်းညှိဝင်ငွေ',
  'Regulation library': 'စည်းမျဉ်းစာကြည့်တိုက်',
  Reporter: 'သတင်းပို့သူ',
  'Reporter identity': 'သတင်းပို့သူအထောက်အထား',
  Roadworthiness: 'လမ်းသွားနိုင်စွမ်းစစ်ဆေးမှု',
  Safety: 'ဘေးကင်းရေး',
  'Safety & incident': 'ဘေးကင်းရေးနှင့်ဖြစ်စဉ်',
  'Searches satisfied': 'ရလဒ်ရရှိရှာဖွေမှု',
  'Service & compliance': 'ဝန်ဆောင်မှုနှင့်စည်းကမ်း',
  'Service class': 'ဝန်ဆောင်မှုအဆင့်',
  SMS: 'SMS',
  'SOS & ticket validation': 'အရေးပေါ်နှင့်လက်မှတ်စိစစ်မှု',
  Speed: 'အမြန်နှုန်း',
  Technical: 'နည်းပညာ',
  'Telematics ingest': 'တယ်လီမက်တစ်အချက်အလက်လက်ခံမှု',
  'Terminal registry': 'ဂိတ်မှတ်ပုံတင်',
  'Treasury posting': 'ဘဏ္ဍာတော်သို့တင်သွင်းမှု',
  'User question (text or voice)': 'အသုံးပြုသူမေးခွန်း (စာသို့မဟုတ်အသံ)',
  Validity: 'သက်တမ်း',
  'Validity if approved': 'အတည်ပြုပါကသက်တမ်း',
  'Vehicle licence': 'ယာဉ်လိုင်စင်',
  'Vehicles not responding': 'အချက်ပြမရသောယာဉ်',
  'Vehicles required / held': 'လိုအပ်ယာဉ် / ထိန်းထားယာဉ်',
  Voice: 'အသံ',
  'Weekly settlement': 'အပတ်စဉ်ရှင်းလင်းမှု',
  Where: 'နေရာ',
  'Insurance (down)': 'အာမခံ (ရပ်ဆိုင်း)',
  'Driving licence registry (degraded)': 'ယာဉ်မောင်းလိုင်စင်မှတ်ပုံတင် (ချို့ယွင်း)',
  'Emergency dispatch (sandbox)': 'အရေးပေါ်စေလွှတ်မှု (စမ်းသပ်)',
  'Enforcement / e-fine (sandbox)': 'အရေးယူမှု / ဒဏ်ကြေး (စမ်းသပ်)',
  'Bay allocated before T-30 min': 'ထွက်ခွာမီ ၃၀မိနစ်တွင်နေရာချထား',
  'Content approved within 24 h': '၂၄နာရီအတွင်းအကြောင်းအရာအတည်ပြု',
  'Helpdesk first response < 4 h': 'အကူအညီဌာနပထမတုံ့ပြန်မှု ၄နာရီအတွင်း',
  'QR validation under 300 ms': 'QR စိစစ်မှု ၃၀၀ms အောက်',
  'Search results under 2 s': 'ရှာဖွေရလဒ် ၂စက္ကန့်အောက်',
  'Citizen assistant — “Ask YanGo”': 'ပြည်သူ့အကူအညီပေးစနစ် — “Ask YanGo”',
  '06–08': '၀၆–၀၈',
  'Sponsored result — journey results (labelled)': 'ကြော်ငြာရလဒ် — ခရီးစဉ်ရလဒ်များ (အညွှန်းတပ်)',

  // --------------------------------------------- licence catalogue & wizard
  Continue: 'ဆက်လုပ်ရန်',
  'Licence type': 'လိုင်စင်အမျိုးအစား',
  Details: 'အသေးစိတ်',
  'Review & submit': 'သုံးသပ်ပြီးတင်သွင်းရန်',
  'Unit fee': 'တစ်ခုချင်းကြေး',
  'SLA target': 'SLA ပန်းတိုင်',
  '5 working days': 'အလုပ်ရက် ၅ ရက်',
  'PO business licence': 'ကုမ္ပဏီလုပ်ငန်းလိုင်စင်',
  'Vehicle / fleet licence': 'ယာဉ်/ယာဉ်အစုလိုင်စင်',
  'Route permit (trayek)': 'လမ်းကြောင်းခွင့်ပြုမိန့်',
  'Special / charter permit': 'အထူး/ငှားရမ်းခွင့်ပြုမိန့်',
  'Driver operating licence': 'ယာဉ်မောင်းလုပ်ကိုင်ခွင့်လိုင်စင်',
  'Crew / conductor card': 'အမှုထမ်း/စပယ်ယာကတ်',
  Flat: 'ပုံသေ',
  'Per vehicle': 'ယာဉ်တစ်စီးလျှင်',
  'Per route + vehicle': 'လမ်းကြောင်း + ယာဉ်လျှင်',
  'Per trip': 'ခရီးစဉ်တစ်ခုလျှင',
  'Per driver': 'ယာဉ်မောင်းတစ်ဦးလျှင်',
  'Per person': 'လူတစ်ဦးလျှင်',
  'Bus company': 'ဘတ်စ်ကားကုမ္ပဏီ',
  PO: 'ကုမ္ပဏီ',
  'Driver or PO': 'ယာဉ်မောင်းသို့မဟုတ်ကုမ္ပဏီ',
  '5 years': '၅ နှစ်',
  '1 year': '၁ နှစ်',
  '1–5 years': '၁–၅ နှစ်',
  '1–3 years': '၁–၃ နှစ်',
  'Company registration': 'ကုမ္ပဏီမှတ်ပုံတင်',
  'Tax ID': 'အခွန်အမှတ်',
  'Director NRC': 'ဒါရိုက်တာမှတ်ပုံတင်',
  'Depot proof': 'ကားဂိတ်ရုံအထောက်အထား',
  'Vehicle registration': 'ယာဉ်မှတ်ပုံတင်',
  'Roadworthiness test': 'လမ်းသွားနိုင်စွမ်းစစ်ဆေးချက်',
  'Vehicle photos': 'ယာဉ်ဓာတ်ပုံများ',
  'Route plan': 'လမ်းကြောင်းအစီအစဉ်',
  Timetable: 'အချိန်ဇယား',
  'Fleet list': 'ယာဉ်စာရင်း',
  'Terminal agreement': 'ဂိတ်သဘောတူညီချက်',
  'Trip plan': 'ခရီးစဉ်အစီအစဉ်',
  'Driving licence': 'ယာဉ်မောင်းလိုင်စင်',
  'National ID': 'နိုင်ငံသားစိစစ်ရေးကတ်',
  'Medical certificate': 'ကျန်းမာရေးလက်မှတ်',
  'Police clearance': 'ရဲစခန်းထောက်ခံစာ',
  'Training certificate': 'သင်တန်းလက်မှတ်',
  Photo: 'ဓာတ်ပုံ',
  'Requirements ': 'လိုအပ်ချက်များ',
  'Uploaded · scanned': 'တင်ပြီး · စကင်ဖတ်ပြီး',
  'Click to attach from the document vault': 'စာရွက်စာတမ်းသိုလှောင်ခန်းမှပူးတွဲရန်နှိပ်ပါ',
  'Fee basis': 'အခကြေးငွေတွက်ပုံ',

  // ------------------------------------------------------- map and chrome
  'Data coverage': 'အချက်အလက်လွှမ်းခြုံမှု',
  'SOS board': 'အရေးပေါ်ဘုတ်',
  'On headway': 'အချိန်မှန်',
  Deviating: 'လမ်းကြောင်းလွဲ',
  Bunching: 'ကားစုပြုံ',
  'Not responding': 'အချက်ပြမရ',
  Blocked: 'ပိတ်ပင်ထား',
  Maintenance: 'ပြုပြင်ထိန်းသိမ်းမှု',
  'Ministry of Transport': 'သယ်ယူပို့ဆောင်ရေးဝန်ကြီးဌာန',
  'Yangon Region Transport Committee': 'ရန်ကုန်တိုင်းသယ်ယူပို့ဆောင်ရေးကော်မတီ',
  'Bus Operator Portal': 'ဘတ်စ်ကားကုမ္ပဏီပေါ်တယ်',
  'Authority back office': 'အာဏာပိုင်ရုံးတွင်းလုပ်ငန်း',
}
